// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pp1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Test111Client is the client API for Test111 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Test111Client interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type test111Client struct {
	cc grpc.ClientConnInterface
}

func NewTest111Client(cc grpc.ClientConnInterface) Test111Client {
	return &test111Client{cc}
}

func (c *test111Client) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/module1.pp1.Test111/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *test111Client) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/module1.pp1.Test111/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Test111Server is the server API for Test111 service.
// All implementations must embed UnimplementedTest111Server
// for forward compatibility
type Test111Server interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTest111Server()
}

// UnimplementedTest111Server must be embedded to have forward compatible implementations.
type UnimplementedTest111Server struct {
}

func (UnimplementedTest111Server) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedTest111Server) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedTest111Server) mustEmbedUnimplementedTest111Server() {}

// UnsafeTest111Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test111Server will
// result in compilation errors.
type UnsafeTest111Server interface {
	mustEmbedUnimplementedTest111Server()
}

func RegisterTest111Server(s grpc.ServiceRegistrar, srv Test111Server) {
	s.RegisterService(&Test111_ServiceDesc, srv)
}

func _Test111_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test111Server).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/module1.pp1.Test111/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test111Server).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test111_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test111Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/module1.pp1.Test111/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test111Server).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Test111_ServiceDesc is the grpc.ServiceDesc for Test111 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test111_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "module1.pp1.Test111",
	HandlerType: (*Test111Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Test111_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Test111_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Test111.proto",
}
